defaults: &defaults
  encoding: unicode
  adapter: postgresql
  host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('DB_PORT') { 5432 } %>
  username: <%= ENV.fetch('DB_USERNAME') { `whoami` } %>
  password: <%= ENV.fetch('DB_PASSWORD') { nil } %>

development:
  <<: *defaults
  database: rails_example_dev

test:
  <<: *defaults
  database: rails_example_test

production:
  <<: *defaults
  database: rails_example_prod

